# 当前版本: 1.0.4

name: 周期自动构建与发布

on:
  # 触发构建的事件
  push:
    branches: 
      - main  # 只有当推送到 'main' 分支时才会触发
  schedule:
    - cron: "0 0 * * *"  # 每天00:00定时执行一次

jobs:
  build:
    runs-on: ubuntu-latest  # 在最新的 Ubuntu 环境中运行构建任务
    steps:
      - name: 第一步 - 检出代码
        uses: actions/checkout@v4  # 检出仓库中的代码

      - name: 第二步 - 构建 GFWList2AGH
        run: |
          # 下载并运行 'release.sh' 脚本来构建 GFWList2AGH
          curl -s "https://raw.githubusercontent.com/hezhijie0327/GFWList2AGH/source/release.sh" | sudo bash

      - name: 第三步 - 发布 GFWList2AGH
        run: |
          # 下载 Git.sh 脚本
          curl -s "https://raw.githubusercontent.com/hezhijie0327/Toolkit/main/Git.sh" > "/tmp/Git.sh"
          # 执行 Git.sh 脚本，进行发布操作
          sudo bash "/tmp/Git.sh" -u "hezhijie0327" -e "hezhijie0327@hotmail.com" -f "." -r "GFWList2AGH" -i "由 GitHub Actions 生成" -m "push"
