# 当前版本: 1.0.8

name: 周期自动构建与发布

on:
  push:
    branches: 
      - main
  schedule:
    - cron: "0 0 * * *"  # 每天00:00定时执行一次
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 第一步 - 克隆当前仓库
        run: |
          git clone https://github.com/XiaomingX/Baned-by-GFW
          cd Baned-by-GFW
          curl -s "https://raw.githubusercontent.com/hezhijie0327/GFWList2AGH/source/release.sh" | sudo bash

      - name: 第二步 - 提交更改并推送
        run: |
          git config --global user.name "XiaomingX"
          git config --global user.email "support@xxxx.com"
          git add .
          git commit -m "自动更新发布 Baned-by-GFW"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用 GitHub 提供的 token 进行身份验证
