# 当前版本: 1.0.8

name: 周期自动构建与发布

on:
  push:
    branches: 
      - main
  schedule:
    - cron: "0 0 * * *"  # 每天00:00定时执行一次
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 第一步 - 克隆当前仓库
        run: |
          git clone https://github.com/XiaomingX/Baned-by-GFW  # 克隆指定仓库
          cd Baned-by-GFW  # 进入仓库目录

      - name: 第二步 - 运行 release.sh 脚本
        run: |
          chmod +x release.sh  # 确保脚本可执行
          ./release.sh  # 运行脚本

      - name: 第三步 - 提交更改并推送
        run: |
          cd Baned-by-GFW  # 确保在正确的目录下
          git config --global user.name "XiaomingX"  # 使用你的 GitHub 用户名
          git config --global user.email "support@xxxx.com"  # 使用你的电子邮件
          git add .
          git commit -m "自动更新发布 Baned-by-GFW"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用 GitHub 提供的 token 进行身份验证
