# 当前版本: 1.0.9

name: 周期自动构建与发布

on:
  push:
    branches: 
      - main
  schedule:
    - cron: "0 0 * * *"  # 每天00:00定时执行一次
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 克隆当前仓库
        run: |
          git clone https://github.com/XiaomingX/Baned-by-GFW
          cd Baned-by-GFW  # 进入仓库目录

      - name: 获取并执行 GFWList2AGH 脚本
        run: |
          cd Baned-by-GFW  # 确保在正确的目录下
          curl -s "https://raw.githubusercontent.com/hezhijie0327/GFWList2AGH/source/release.sh" | sudo bash

      - name: 配置 Git 用户信息
        run: |
          cd Baned-by-GFW  # 确保在正确的目录下
          git config --global user.name "XiaomingX"
          git config --global user.email "support@xxxx.com"

      - name: 提交更改并推送
        run: |
          cd Baned-by-GFW  # 确保在正确的目录下
          git add .
          # 检查是否有更改
          git diff --exit-code || git commit -m "自动更新发布 Baned-by-GFW"
          git push https://xiamingx:${{ secrets.GITHUB_TOKEN }}@github.com/XiaomingX/Baned-by-GFW.git main
